### ISSUE TITLE
Tag task through the API

### ISSUE THREAD

**Issue by PasLoin** [coopcycle/coopcycle-plugins#15]
Transfered issue from here : https://github.com/coopcycle/coopcycle-wp/issues/4

When sending an API payload to create a delivery, we should be able to send tags.
The task should be tagged accordingly.
----------------------------------------------
I think the tag must be configurable in admin/api/apps

**Comment by alexsegura** [comment]
Closed in coopcycle/coopcycle-web#1097

You can now tag stores, and deliveries created for those stores will inherit the tags

**Comment by PasLoin** [comment]
Only the pickup is tagged ; the drop associated not.
